Repository Coderockr/vitrine-social, pull requests merged in 2018-06, with the labels that each got.

#132 Address as embedded struct
  docs/api.apib
  docs/index.html
  server/db/repo/organization.go
  server/handlers/json-structs.go
  server/handlers/organization.go
  server/model/model.go
Labels: Category: Backend, Stage: Review, Type: Improvement

#145 Issue 142
  frontend/src/components/Header/Header.js
  frontend/src/components/Header/styles.module.scss
  frontend/src/components/ItemIndicator/ItemIndicator.js
  frontend/src/components/OrganizationProfileForm/styles.module.scss
  frontend/src/components/RequestCard/RequestCard.js
  frontend/src/components/RequestCard/styles.module.scss
  frontend/src/components/RequestDetails/RequestDetails.js
  frontend/src/components/RequestDetails/styles.module.scss
  frontend/src/components/RequestForm/RequestForm.js
  frontend/src/components/RequestForm/styles.module.scss
  frontend/src/components/Requests/Requests.js
  frontend/src/components/Requests/styles.module.scss
  frontend/src/components/UploadImages/UploadImages.js
  frontend/src/containers/Login/Login.js
  frontend/src/containers/Login/styles.module.scss
  frontend/src/containers/OrganizationProfile/OrganizationProfile.js
  frontend/src/utils/api.js
  frontend/src/utils/auth.js
  frontend/src/utils/styles/common.scss
  frontend/src/utils/styles/global.module.scss
Labels: Stage: Review

#61 Issue 37
  devops/migrations/20180608142213-need-create-update-date.sql
  docs/api.apib
  docs/index.html
  server/cmd/serve.go
  server/db/repo/organization.go
  server/db/repo/search.go
  server/handlers/json-structs.go
  server/handlers/search.go
  server/handlers/success.go
  server/model/model.go
  server/storage/storage_test.go
Labels: WIP

#151 Enable update status on endpoint update need
  docs/api.apib
  docs/index.html
  server/db/repo/need.go
  server/handlers/need.go
  server/handlers/need_test.go
Labels: Stage: Review

#153 Change icon field to slug
  devops/migrations/20180611105900-change-icon-slug.sql
  docs/api.apib
  server/db/repo/search.go
  server/handlers/category.go
  server/handlers/json-structs.go
  server/handlers/need.go
  server/handlers/organization.go
  server/handlers/search.go
  server/model/model.go
Labels: Stage: Review

#154 Hotfix search without text required and orderBy
  docs/api.apib
  docs/index.html
  server/db/repo/search.go
  server/handlers/search.go
Labels: Stage: Review

#157 Issue 146
  frontend/src/components/Categories/Categories.js
  frontend/src/components/Requests/Requests.js
  frontend/src/containers/Home/Home.js
  frontend/src/containers/OrganizationProfile/OrganizationProfile.js
Labels: Stage: Review

#158 Implemented redirect on login and link to organization from requestcard
  frontend/src/App.js
  frontend/src/components/RequestCard/RequestCard.js
  frontend/src/components/RequestForm/RequestForm.js
  frontend/src/containers/Login/Login.js
  frontend/src/containers/OrganizationProfile/OrganizationProfile.js
Labels: Stage: Review

#159 Fix search handler and need model
  devops/migrations/20180612101731-change-unity-unit.sql
  docs/api.apib
  docs/index.html
  server/db/repo/need.go
  server/db/repo/search.go
  server/handlers/auth_test.go
  server/handlers/json-structs.go
  server/handlers/need.go
  server/handlers/need_test.go
  server/handlers/organization.go
  server/handlers/search.go
  server/model/model.go
Labels: Stage: Review

#164 Add github issue and PR templates
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Stage: Review

#161 Implemented contact form with calls to API and added ResponseFeedback
  frontend/src/components/ContactForm/ContactForm.js
  frontend/src/components/ContactForm/styles.module.scss
  frontend/src/components/RequestDetails/RequestDetails.js
Labels: Stage: Review

#163 Fix need response create
  devops/migrations/20180612161737-fix-need-response.sql
  server/cmd/serve.go
  server/db/repo/need_response.go
  server/handlers/need_response.go
  server/model/model.go
Labels: Stage: Review

#165 Fix params number
  server/db/repo/search.go
Labels: Stage: Review

#167 Issue 147
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/Categories/Categories.js
  frontend/src/components/Categories/styles.module.scss
  frontend/src/components/CategoriesItem/CategoriesItem.js
  frontend/src/components/CategoriesItem/styles.module.scss
  frontend/src/components/Layout/Layout.js
  frontend/src/components/Requests/Requests.js
  frontend/src/components/Requests/styles.module.scss
  frontend/src/components/Search/Search.js
  frontend/src/components/Search/styles.module.scss
  frontend/src/containers/Home/Home.js
  frontend/src/containers/Results/Results.js
  frontend/src/containers/Results/index.js
  frontend/src/reducers/index.js
  frontend/src/reducers/requests.js
  frontend/src/utils/styles/common.scss
  frontend/src/utils/styles/global.module.scss
  frontend/yarn.lock
Labels: Stage: Review

#170 Fix status params and search by organization name
  server/db/repo/search.go
Labels: Stage: Review

#169 Implemented Pagination
  frontend/src/components/Pagination/Pagination.js
  frontend/src/containers/Home/Home.js
  frontend/src/containers/Results/Results.js
Labels: Stage: Review

#174 Implemented ErrorCard and added to Categories, Requests, and Organiza…
  frontend/src/components/Categories/Categories.js
  frontend/src/components/ErrorCard/ErrorCard.js
  frontend/src/components/ErrorCard/index.js
  frontend/src/components/ErrorCard/styles.module.scss
  frontend/src/components/Requests/Requests.js
  frontend/src/components/Search/styles.module.scss
  frontend/src/containers/Home/Home.js
  frontend/src/containers/OrganizationProfile/OrganizationProfile.js
  frontend/src/containers/Results/Results.js
  frontend/src/utils/styles/colors.js
Labels: Stage: Review

#173 Save param unit
  server/handlers/create_need.go
  server/handlers/create_need_test.go
Labels: Stage: Review

#176 Reset Password Handler
  docs/api.apib
  docs/index.html
  server/cmd/create.go
  server/cmd/impersonate.go
  server/cmd/serve.go
  server/handlers/auth.go
  server/handlers/auth_test.go
  server/handlers/jwt.go
  server/handlers/update_password.go
  server/model/model.go
Labels: Stage: Review

#178 Issue 172
  frontend/public/assets/images/brand.svg
  frontend/public/assets/images/categories.svg
  frontend/public/assets/images/coderockr.svg
  frontend/public/assets/images/community.svg
  frontend/public/assets/images/hands.svg
  frontend/public/assets/images/heart.svg
  frontend/src/App.js
  frontend/src/components/Header/Header.js
  frontend/src/containers/About/About.js
  frontend/src/containers/About/index.js
  frontend/src/containers/About/styles.module.scss
Labels: Stage: Review

#179 Issue 177
  frontend/.eslintrc
  frontend/src/components/Footer/Footer.js
  frontend/src/components/Footer/index.js
  frontend/src/components/Footer/styles.module.scss
  frontend/src/components/Layout/Layout.js
  frontend/src/containers/About/About.js
  frontend/src/containers/About/styles.module.scss
  frontend/src/containers/Login/Login.js
  frontend/src/containers/Login/styles.module.scss
  frontend/src/containers/OrganizationProfile/OrganizationProfile.js
  frontend/src/utils/styles/antTheme.less
Labels: Stage: Review

#182 Update create.go
  server/cmd/create.go
  server/config/dev.env.dist
Labels: Stage: Review

#181 Implemented contact page and fixed About page
  frontend/src/App.js
  frontend/src/components/BottomNotification/BottomNotification.js
  frontend/src/components/BottomNotification/styles.module.scss
  frontend/src/components/Footer/styles.module.scss
  frontend/src/containers/About/About.js
  frontend/src/containers/About/styles.module.scss
  frontend/src/containers/Contact/Contact.js
  frontend/src/containers/Contact/index.js
  frontend/src/containers/Contact/styles.module.scss
  frontend/src/containers/Login/Login.js
  frontend/src/utils/styles/global.module.scss
Labels: Stage: Review

#184 Implemented change password compenent and reset password container
  frontend/src/App.js
  frontend/src/components/ChangePassword/ChangePassword.js
  frontend/src/components/ChangePassword/index.js
  frontend/src/components/ChangePassword/styles.module.scss
  frontend/src/components/Layout/Layout.js
  frontend/src/containers/Login/styles.module.scss
  frontend/src/containers/ResetPassword/ResetPassword.js
  frontend/src/containers/ResetPassword/index.js
  frontend/src/containers/ResetPassword/styles.module.scss
  frontend/src/containers/Results/Results.js
  frontend/src/utils/styles/global.module.scss
Labels: Stage: Review

#185 Implemented update password
  frontend/src/components/ChangePassword/ChangePassword.js
  frontend/src/components/Layout/Layout.js
  frontend/src/components/ResponseFeedback/ResponseFeedback.js
  frontend/src/components/ResponseFeedback/styles.module.scss
  frontend/src/containers/OrganizationProfile/OrganizationProfile.js
  frontend/src/containers/OrganizationProfile/styles.module.scss
  frontend/src/utils/styles/global.module.scss
Labels: Stage: Review

#188 Implemented user menu and log out
  frontend/src/components/Header/Header.js
  frontend/src/components/Header/styles.module.scss
  frontend/src/containers/Login/Login.js
  frontend/src/containers/Login/styles.module.scss
  frontend/src/utils/api.js
  frontend/src/utils/styles/common.scss
  frontend/src/utils/styles/global.module.scss
Labels: Stage: Review

#190 make build
  Makefile
Labels: Stage: Review

#194 Issue 191
  .gitignore
  .travis.yml
  Makefile
  devops/dbconfig.yml
  devops/deploy.sh
  frontend/.env.production
  vitrinesocial.pem.enc
Labels: Stage: Review

#196 Added logo to header and removed images functionality
  frontend/public/assets/images/vitrinesocial.svg
  frontend/src/components/Header/Header.js
  frontend/src/components/Header/styles.module.scss
  frontend/src/components/OrganizationProfileForm/OrganizationProfileForm.js
  frontend/src/components/RequestDetails/RequestDetails.js
  frontend/src/components/RequestForm/RequestForm.js
  frontend/src/containers/OrganizationProfile/OrganizationProfile.js
Labels: Stage: Review

#197 Change build to master branch on travis
  .travis.yml
Labels: Stage: Review

#198 Hotfix travis migrations
  .travis.yml
  devops/deploy.sh
Labels: Stage: Review

#203 Fix need update_at param
  server/db/repo/need.go
  server/handlers/need.go
Labels: Stage: Review

#205 After deploy command to invalid cloudfront cache
  .travis.yml
Labels: Stage: Review

#207 Migrations on dev
  Makefile
  devops/dbconfig.yml
Labels: Stage: Review

#206 Changed favicon, adjusted indentation and fixed logo path
  frontend/public/favicon.png
  frontend/src/components/Header/Header.js
  frontend/src/components/OrganizationProfileForm/OrganizationProfileForm.js
  frontend/src/components/RequestDetails/RequestDetails.js
  frontend/src/components/RequestForm/RequestForm.js
  frontend/src/containers/Home/Home.js
  frontend/src/containers/OrganizationProfile/OrganizationProfile.js
Labels: Stage: Review
